# Generated by Django 5.2.17 on 2026-08-13 01:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('mode', models.CharField(choices=[('CONTEST', '대회'), ('PRACTICE_STOCK', '주식 연습'), ('PRACTICE_CRYPTO', '코인 연습'), ('PRACTICE_ALT', '대체자산 연습')], max_length=20, verbose_name='모드')),
                ('cash', models.BigIntegerField(default=0, verbose_name='현금(원)')),
                ('initial_capital', models.BigIntegerField(default=100000000, help_text='수익률 기준선이자 초기화 목표값', verbose_name='시작 자본(원)')),
                ('is_frozen', models.BooleanField(default=False, help_text='대회 종료 후 동결 → 주문 불가', verbose_name='동결 여부')),
                ('reset_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 초기화')),
            ],
            options={
                'verbose_name': '계좌',
                'verbose_name_plural': '계좌',
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('name', models.CharField(max_length=50, verbose_name='키 이름')),
                ('key_prefix', models.CharField(db_index=True, max_length=16, verbose_name='키 접두')),
                ('key_hash', models.CharField(help_text='평문은 저장하지 않는다', max_length=64, unique=True, verbose_name='키 해시(sha256)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 사용')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='폐기 시각')),
            ],
            options={
                'verbose_name': 'Open API 키',
                'verbose_name_plural': 'Open API 키',
                'db_table': 'api_key',
            },
        ),
        migrations.CreateModel(
            name='RateLimitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField(verbose_name='윈도우 시작(분 절삭)')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='호출 수')),
            ],
            options={
                'verbose_name': 'API 유량 카운터',
                'verbose_name_plural': 'API 유량 카운터',
                'db_table': 'rate_limit_counter',
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('asset_class', models.CharField(choices=[('STOCK', '주식'), ('CRYPTO', '코인'), ('ALT', '대체자산')], max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('sort_order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '관심종목',
                'verbose_name_plural': '관심종목',
                'db_table': 'watchlist',
                'ordering': ['sort_order', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('display_name', models.CharField(blank=True, max_length=30, verbose_name='표시명')),
                ('avatar', models.ImageField(blank=True, max_length=200, null=True, upload_to='avatars/', verbose_name='프로필 이미지')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원',
                'db_table': 'member',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
