# Generated by Django 5.2.17 on 2026-08-13 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contest',
            field=models.ForeignKey(blank=True, help_text='대회 계좌면 값이 있고, 연습 계좌면 비어 있다', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='contests.contest', verbose_name='대회'),
        ),
        migrations.AddField(
            model_name='account',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='account',
            field=models.ForeignKey(help_text='이 키로 낸 주문은 항상 이 계좌로 들어간다', on_delete=django.db.models.deletion.PROTECT, related_name='api_keys', to='accounts.account', verbose_name='주문 대상 계좌'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
        migrations.AddField(
            model_name='ratelimitcounter',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_counters', to='accounts.apikey'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['member', 'mode'], name='account_idx_member_mode'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['contest'], name='account_idx_contest'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('contest__isnull', True)), fields=('member', 'mode'), name='account_uniq_practice_mode'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('contest__isnull', False)), fields=('member', 'contest'), name='account_uniq_contest'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contest__isnull', False), ('mode', 'CONTEST')), models.Q(models.Q(('mode', 'CONTEST'), _negated=True), ('contest__isnull', True)), _connector='OR'), name='account_ck_mode_contest_match'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['member', 'is_active'], name='api_key_idx_member_active'),
        ),
        migrations.AddIndex(
            model_name='ratelimitcounter',
            index=models.Index(fields=['window_start'], name='rate_limit_idx_window'),
        ),
        migrations.AddConstraint(
            model_name='ratelimitcounter',
            constraint=models.UniqueConstraint(fields=('api_key', 'window_start'), name='rate_limit_uniq_window'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('member', 'asset_class', 'symbol'), name='watchlist_uniq_symbol'),
        ),
    ]
