# Generated by Django 5.2.17 on 2026-08-13 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='account_idx_contest',
        ),
    ]
