# Generated by Django 5.2.17 on 2026-08-13 01:21

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ★ 손으로 추가한 오퍼레이션 — `vector` 확장은 **테이블보다 먼저** 있어야 한다.
        #   KnowledgeDocument.embedding 이 vector(384) 타입이라, 확장이 없으면
        #   CREATE TABLE 이 "type vector does not exist" 로 실패한다 (05 문서 2장).
        #   CREATE EXTENSION IF NOT EXISTS vector 로 번역되므로 여러 번 돌아도 안전하다.
        #
        #   pg_cron 은 여기서 켤 수 없다 — 슈퍼유저 권한이 필요해 Supabase
        #   대시보드에서 수동으로 활성화한다.
        VectorExtension(),
        migrations.CreateModel(
            name='SavedSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('source_url', models.TextField(blank=True, verbose_name='원본 URL')),
                ('data', models.JSONField(default=dict, help_text='헤더 + 행 배열 (편집된 상태 그대로)', verbose_name='표 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '저장한 표',
                'verbose_name_plural': '저장한 표',
                'db_table': 'saved_sheet',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('CRYPTO', '코인'), ('STOCK', '주식'), ('MARKET', '시장'), ('MY_PORTFOLIO', '내 포트폴리오'), ('CONTEST', '대회')], max_length=20, verbose_name='분석 범위')),
                ('model', models.CharField(max_length=40, verbose_name='모델명')),
                ('tokens_in', models.IntegerField(default=0, verbose_name='입력 토큰')),
                ('tokens_out', models.IntegerField(default=0, verbose_name='출력 토큰')),
                ('latency_ms', models.IntegerField(default=0, verbose_name='응답 시간(ms)')),
                ('is_error', models.BooleanField(default=False, help_text='실패는 쿼터를 차감하지 않는다', verbose_name='실패')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI 사용 로그',
                'verbose_name_plural': 'AI 사용 로그',
                'db_table': 'ai_usage_log',
                'indexes': [models.Index(fields=['member', 'created_at'], name='ai_usage_idx_member_date')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('category', models.CharField(db_index=True, max_length=30, verbose_name='카테고리')),
                ('content', models.TextField(help_text='사용자 입력은 2000자 제한', verbose_name='본문')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='배치(backfill_embeddings)가 채운다. 비어 있으면 검색에 나오지 않는다', null=True, verbose_name='임베딩')),
                ('source', models.CharField(choices=[('SEED', '시드'), ('USER', '사용자 추가'), ('BATCH', '배치 수집')], default='USER', max_length=10)),
                ('is_approved', models.BooleanField(db_index=True, default=False, help_text='검토 대기 상태(False)인 문서는 검색 결과에 나오지 않는다', verbose_name='승인')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_docs', to=settings.AUTH_USER_MODEL, verbose_name='승인한 운영자')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_docs', to=settings.AUTH_USER_MODEL, verbose_name='추가한 회원')),
            ],
            options={
                'verbose_name': '지식 문서',
                'verbose_name_plural': '지식 문서',
                'db_table': 'knowledge_document',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='knowledge_hnsw_cosine', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='WebFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='요청 URL')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='응답 코드')),
                ('size_bytes', models.IntegerField(default=0, verbose_name='응답 크기')),
                ('elapsed_ms', models.IntegerField(default=0, verbose_name='소요 시간(ms)')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='차단됨')),
                ('block_reason', models.CharField(blank=True, choices=[('PRIVATE_IP', '사설 IP'), ('SCHEME', '허용되지 않은 스킴'), ('PORT', '허용되지 않은 포트'), ('REDIRECT', '리디렉션 최종 URL 거부'), ('CONTENT_TYPE', 'HTML 이 아님'), ('SIZE', '크기 초과'), ('CREDENTIALS', 'URL 에 자격증명 포함')], max_length=50, verbose_name='차단 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='web_fetch_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '웹 수집 로그',
                'verbose_name_plural': '웹 수집 로그',
                'db_table': 'web_fetch_log',
                'indexes': [models.Index(fields=['member', 'created_at'], name='webfetch_idx_member_date')],
            },
        ),
    ]
