# Generated by Django 5.2.17 on 2026-08-13 01:21

import contests.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('name', models.CharField(max_length=100, verbose_name='대회명')),
                ('slug', models.SlugField(help_text='/contests/rfm-1/ — id 노출을 피한다', unique=True, verbose_name='URL 식별자')),
                ('description', models.TextField(blank=True, verbose_name='규칙 안내(마크다운)')),
                ('asset_class', models.CharField(choices=[('STOCK', '주식'), ('CRYPTO', '코인'), ('ALT', '대체자산')], default='STOCK', help_text='1차는 STOCK 만 허용한다. 코인·대체자산 대회는 v2.2', max_length=10, verbose_name='자산군')),
                ('status', models.CharField(choices=[('DRAFT', '준비중'), ('UPCOMING', '모집중'), ('ONGOING', '진행중'), ('SETTLING', '정산중'), ('CLOSED', '종료'), ('CANCELLED', '취소')], db_index=True, default='DRAFT', max_length=10, verbose_name='상태')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('entry_deadline', models.DateField(blank=True, help_text='비우면 종료까지', null=True, verbose_name='참가 신청 마감')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='비우면 무제한', null=True, verbose_name='정원')),
                ('approval_mode', models.CharField(choices=[('AUTO', '자동 승인'), ('MANUAL', '운영자 승인')], default='AUTO', max_length=10, verbose_name='승인 방식')),
                ('visibility', models.CharField(choices=[('PUBLIC', '공개'), ('LINK', '링크 있는 사람만'), ('PRIVATE', '비공개')], default='PUBLIC', max_length=10, verbose_name='공개 범위')),
                ('portfolio_visibility', models.CharField(choices=[('ALL', '전체 공개'), ('TOP_N', '상위 N명만'), ('SELF_ONLY', '본인만')], default='ALL', help_text="동아리 대회는 ALL 이 기본. 벤치마크의 '50등 이후 조회 불가' 결함에 대한 대응", max_length=10, verbose_name='포트폴리오 공개 범위')),
                ('portfolio_visible_top_n', models.PositiveIntegerField(default=50, verbose_name='공개 상위 N명')),
                ('initial_capital', models.BigIntegerField(default=100000000, verbose_name='시작 자본(원)')),
                ('fee_bp', models.PositiveSmallIntegerField(default=10, verbose_name='매매 수수료(bp)')),
                ('tax_bp', models.PositiveSmallIntegerField(default=20, verbose_name='매도세(bp)')),
                ('rule_set', models.JSONField(default=contests.models.default_rule_set, verbose_name='규칙')),
                ('entry_requirement', models.JSONField(blank=True, default=dict, help_text='{"min_learning_points": 30} 처럼. 1차 기본값은 제한 없음', verbose_name='참가 조건')),
                ('universe_frozen_at', models.DateTimeField(blank=True, null=True, verbose_name='유니버스 고정 시각')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contests', to=settings.AUTH_USER_MODEL, verbose_name='만든 운영자')),
            ],
            options={
                'verbose_name': '대회',
                'verbose_name_plural': '대회',
                'db_table': 'contest',
            },
        ),
        migrations.CreateModel(
            name='ContestSectorWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_code', models.CharField(max_length=20, verbose_name='업종 코드')),
                ('sector_name', models.CharField(blank=True, max_length=40, verbose_name='업종명')),
                ('market_weight_pct', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='시장 섹터 비중 %')),
                ('limit_pct', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='허용 한도 %')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_weights', to='contests.contest')),
            ],
            options={
                'verbose_name': '대회 섹터 비중',
                'verbose_name_plural': '대회 섹터 비중',
                'db_table': 'contest_sector_weight',
            },
        ),
        migrations.CreateModel(
            name='ContestUniverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=6, verbose_name='종목코드')),
                ('name', models.CharField(max_length=60, verbose_name='시작 시점 종목명')),
                ('market', models.CharField(max_length=10, verbose_name='시장')),
                ('sector_code', models.CharField(blank=True, max_length=20, verbose_name='업종 코드')),
                ('sector_name', models.CharField(blank=True, help_text='KRX 업종분류 (GICS 아님)', max_length=40, verbose_name='업종명')),
                ('is_tradable_at_start', models.BooleanField(default=True, help_text='참고용. 실제 판정은 최신값으로 한다', verbose_name='시작 시점 거래 가능')),
                ('frozen_at', models.DateTimeField(verbose_name='고정 시각')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universe', to='contests.contest')),
            ],
            options={
                'verbose_name': '대회 종목 스냅샷',
                'verbose_name_plural': '대회 종목 스냅샷',
                'db_table': 'contest_universe',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('nickname', models.CharField(help_text='랭킹 표시명. 실명은 노출하지 않는다', max_length=20, verbose_name='별칭')),
                ('status', models.CharField(choices=[('PENDING', '승인 대기'), ('APPROVED', '승인'), ('REJECTED', '거절'), ('DISQUALIFIED', '실격'), ('WITHDRAWN', '포기')], db_index=True, default='PENDING', max_length=15, verbose_name='상태')),
                ('is_ranked', models.BooleanField(default=True, help_text='실격은 이 값을 False 로만 만든다', verbose_name='랭킹 포함')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='신청 시각')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인 시각')),
                ('disqualified_at', models.DateTimeField(blank=True, null=True, verbose_name='실격 시각')),
                ('disqualified_reason', models.CharField(blank=True, max_length=200, verbose_name='실격 사유')),
                ('account', models.OneToOneField(blank=True, help_text='승인 시점에 생성된다. PENDING 상태에서는 비어 있다', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participation', to='accounts.account')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='contests.contest')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '대회 참가',
                'verbose_name_plural': '대회 참가',
                'db_table': 'participation',
            },
        ),
        migrations.CreateModel(
            name='IntradaySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(verbose_name='시각(10분 간격)')),
                ('return_pct', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='수익률 %')),
                ('nav', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='기준가')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intraday_snapshots', to='contests.participation')),
            ],
            options={
                'verbose_name': '장중 스냅샷',
                'verbose_name_plural': '장중 스냅샷',
                'db_table': 'intraday_snapshot',
            },
        ),
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='영업일(KST)')),
                ('cash', models.BigIntegerField(verbose_name='현금')),
                ('position_value', models.BigIntegerField(verbose_name='보유 평가액')),
                ('total_asset', models.BigIntegerField(verbose_name='순자산')),
                ('nav', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='기준가(시작=1000)')),
                ('daily_return_pct', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='전일 대비 %')),
                ('cumulative_return_pct', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='누적 수익률 %')),
                ('position_count', models.PositiveIntegerField(default=0, verbose_name='보유 종목 수')),
                ('invested_ratio_pct', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='편입비 %')),
                ('buy_amount', models.BigIntegerField(default=0, verbose_name='당일 매수')),
                ('sell_amount', models.BigIntegerField(default=0, verbose_name='당일 매도')),
                ('fee_amount', models.BigIntegerField(default=0, verbose_name='당일 수수료')),
                ('tax_amount', models.BigIntegerField(default=0, verbose_name='당일 매도세')),
                ('holdings', models.JSONField(default=list, verbose_name='보유 종목 원본')),
                ('sector_weights', models.JSONField(default=list, verbose_name='섹터 비중')),
                ('violations', models.JSONField(default=list, verbose_name='한도 위반 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='contests.participation')),
            ],
            options={
                'verbose_name': '일별 스냅샷',
                'verbose_name_plural': '일별 스냅샷',
                'db_table': 'daily_snapshot',
            },
        ),
        migrations.CreateModel(
            name='ContestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='최종 순위')),
                ('return_score', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='수익 원점수(누적 수익률)')),
                ('return_percentile', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='수익 백분위')),
                ('management_score', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='관리 원점수')),
                ('management_percentile', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='관리 백분위')),
                ('port_hhi', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='포트 HHI')),
                ('pnl_hhi', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='손익 HHI')),
                ('final_score', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='최종 점수(백분위 가중합)')),
                ('grade', models.CharField(blank=True, help_text='A+ ~ F', max_length=3, verbose_name='등급')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='확정 시각')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='contests.contest')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='contests.participation')),
            ],
            options={
                'verbose_name': '대회 최종 결과',
                'verbose_name_plural': '대회 최종 결과',
                'db_table': 'contest_result',
            },
        ),
        migrations.CreateModel(
            name='ContestRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='영업일(KST)')),
                ('rank', models.PositiveIntegerField(blank=True, help_text="비우면 실격·포기. 화면에는 '-' 로 표시", null=True, verbose_name='순위')),
                ('prev_rank', models.PositiveIntegerField(blank=True, help_text='등락(3↑) 표시용', null=True, verbose_name='전일 순위')),
                ('nav', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='기준가')),
                ('cumulative_return_pct', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='누적 수익률 %')),
                ('daily_return_pct', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='일간 수익률 %')),
                ('position_count', models.PositiveIntegerField(default=0, verbose_name='보유 종목 수')),
                ('invested_ratio_pct', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='편입비 %')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='contests.contest')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='contests.participation')),
            ],
            options={
                'verbose_name': '대회 랭킹',
                'verbose_name_plural': '대회 랭킹',
                'db_table': 'contest_ranking',
            },
        ),
        migrations.CreateModel(
            name='RuleViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(choices=[('POSITION_LIMIT', '종목 비중 한도'), ('SECTOR_LIMIT', '섹터 비중 한도'), ('SMALL_CAP_LIMIT', '소형주 합계 한도'), ('WEEKLY_TURNOVER', '주간 회전율')], max_length=30, verbose_name='규칙')),
                ('date', models.DateField(verbose_name='발생 영업일')),
                ('severity', models.CharField(choices=[('WARN', '경고(가격 변동에 의한 초과)'), ('BLOCK', '차단(주문 거부)')], default='WARN', max_length=10)),
                ('detail', models.JSONField(default=dict, help_text='현재 비중·한도·초과분', verbose_name='상세')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='해소 여부')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='해소 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='contests.participation')),
            ],
            options={
                'verbose_name': '규칙 위반',
                'verbose_name_plural': '규칙 위반',
                'db_table': 'rule_violation',
            },
        ),
        migrations.CreateModel(
            name='SnapshotHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=60)),
                ('sector_code', models.CharField(blank=True, max_length=20)),
                ('qty', models.DecimalField(decimal_places=8, max_digits=28)),
                ('avg_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='그날 종가')),
                ('value', models.BigIntegerField(verbose_name='평가액')),
                ('weight_pct', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='순자산 대비 비중 %')),
                ('pnl', models.BigIntegerField(default=0, verbose_name='평가손익')),
                ('pnl_pct', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='평가손익률 %')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contests.contest')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contests.participation')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_rows', to='contests.dailysnapshot')),
            ],
            options={
                'verbose_name': '스냅샷 보유 종목',
                'verbose_name_plural': '스냅샷 보유 종목',
                'db_table': 'snapshot_holding',
            },
        ),
        migrations.CreateModel(
            name='WeeklyTurnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='주 시작(월요일 KST)')),
                ('buy_amount', models.BigIntegerField(default=0, verbose_name='매수 합계')),
                ('sell_amount', models.BigIntegerField(default=0, verbose_name='매도 합계')),
                ('avg_asset', models.BigIntegerField(default=0, verbose_name='평균 운용금액')),
                ('turnover_pct', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='회전율 %')),
                ('is_violation', models.BooleanField(default=False, verbose_name='기준 미달')),
                ('is_confirmed', models.BooleanField(default=False, help_text='False 면 이번 주 잠정치', verbose_name='확정 여부')),
                ('violation_seq', models.PositiveSmallIntegerField(default=0, verbose_name='확정 위반 누적')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_turnovers', to='contests.participation')),
            ],
            options={
                'verbose_name': '주간 회전율',
                'verbose_name_plural': '주간 회전율',
                'db_table': 'weekly_turnover',
            },
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['status', 'start_date'], name='contest_idx_status_start'),
        ),
        migrations.AddConstraint(
            model_name='contest',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='contest_ck_date_order'),
        ),
        migrations.AddConstraint(
            model_name='contestsectorweight',
            constraint=models.UniqueConstraint(fields=('contest', 'sector_code'), name='sector_weight_uniq'),
        ),
        migrations.AddConstraint(
            model_name='contestuniverse',
            constraint=models.UniqueConstraint(fields=('contest', 'symbol'), name='universe_uniq_symbol'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['contest', 'status'], name='part_idx_contest_status'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('contest', 'member'), name='participation_uniq_member'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('contest', 'nickname'), name='participation_uniq_nickname'),
        ),
        migrations.AddIndex(
            model_name='intradaysnapshot',
            index=models.Index(fields=['at'], name='intraday_idx_at'),
        ),
        migrations.AddConstraint(
            model_name='intradaysnapshot',
            constraint=models.UniqueConstraint(fields=('participation', 'at'), name='intraday_uniq_part_at'),
        ),
        migrations.AddIndex(
            model_name='dailysnapshot',
            index=models.Index(fields=['date'], name='daily_snapshot_idx_date'),
        ),
        migrations.AddConstraint(
            model_name='dailysnapshot',
            constraint=models.UniqueConstraint(fields=('participation', 'date'), name='daily_snapshot_uniq_pd'),
        ),
        migrations.AddIndex(
            model_name='contestresult',
            index=models.Index(fields=['contest', 'final_rank'], name='result_idx_contest_rank'),
        ),
        migrations.AddConstraint(
            model_name='contestresult',
            constraint=models.UniqueConstraint(fields=('contest', 'participation'), name='result_uniq_cp'),
        ),
        migrations.AddIndex(
            model_name='contestranking',
            index=models.Index(fields=['contest', 'date', 'rank'], name='ranking_idx_contest_date'),
        ),
        migrations.AddConstraint(
            model_name='contestranking',
            constraint=models.UniqueConstraint(fields=('contest', 'participation', 'date'), name='ranking_uniq_cpd'),
        ),
        migrations.AddIndex(
            model_name='ruleviolation',
            index=models.Index(fields=['date', 'rule'], name='violation_idx_date_rule'),
        ),
        migrations.AddConstraint(
            model_name='ruleviolation',
            constraint=models.UniqueConstraint(fields=('participation', 'rule', 'date'), name='violation_uniq_prd'),
        ),
        migrations.AddIndex(
            model_name='snapshotholding',
            index=models.Index(fields=['contest', 'date', 'symbol'], name='snap_hold_idx_contest_date'),
        ),
        migrations.AddIndex(
            model_name='snapshotholding',
            index=models.Index(fields=['participation', 'symbol', 'date'], name='snap_hold_idx_part_symbol'),
        ),
        migrations.AddConstraint(
            model_name='snapshotholding',
            constraint=models.UniqueConstraint(fields=('snapshot', 'symbol'), name='snapshot_holding_uniq'),
        ),
        migrations.AddConstraint(
            model_name='weeklyturnover',
            constraint=models.UniqueConstraint(fields=('participation', 'week_start'), name='turnover_uniq_part_week'),
        ),
    ]
