# Generated by Django 5.2.17 on 2026-08-13 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('slug', models.SlugField(unique=True, verbose_name='URL 식별자')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='본문(마크다운)')),
                ('last_verified_at', models.DateField(blank=True, help_text="화면 상단에 'YYYY-MM-DD 기준' 으로 표시한다", null=True, verbose_name='최종 확인일')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬')),
                ('is_published', models.BooleanField(default=True, verbose_name='공개')),
            ],
            options={
                'verbose_name': '학습 가이드',
                'verbose_name_plural': '학습 가이드',
                'db_table': 'guide',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('key', models.SlugField(help_text='macro-indicators 등. URL 과 진행률 이관에 쓴다', unique=True, verbose_name='레슨 키')),
                ('group', models.CharField(db_index=True, help_text='매크로 / 산업 / 기본적 / 기술적 / 일자별 / 도구', max_length=30, verbose_name='그룹')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='그룹 내 정렬')),
                ('content', models.JSONField(default=dict, verbose_name='본문')),
                ('max_points', models.PositiveSmallIntegerField(default=10, verbose_name='최대 획득 포인트')),
                ('is_published', models.BooleanField(default=True, help_text='초안 숨김', verbose_name='공개')),
            ],
            options={
                'verbose_name': '학습 레슨',
                'verbose_name_plural': '학습 레슨',
                'db_table': 'lesson',
                'ordering': ['group', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_points', models.PositiveSmallIntegerField(default=0, verbose_name='획득 포인트')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시각')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_rows', to='learning.lesson')),
            ],
            options={
                'verbose_name': '학습 진행률',
                'verbose_name_plural': '학습 진행률',
                'db_table': 'learning_progress',
                'constraints': [models.UniqueConstraint(fields=('member', 'lesson'), name='learning_progress_uniq')],
            },
        ),
    ]
