# Generated by Django 5.2.17 on 2026-08-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=20, unique=True, verbose_name='마켓 코드')),
                ('rank', models.PositiveIntegerField(db_index=True, verbose_name='순위')),
                ('trade_price', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='현재가')),
                ('acc_trade_price_24h', models.BigIntegerField(default=0, help_text='랭킹 기준값', verbose_name='24시간 거래대금(KRW)')),
                ('change_rate', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='등락률 %')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '코인 랭킹',
                'verbose_name_plural': '코인 랭킹',
                'db_table': 'crypto_rank',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='IndexCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(verbose_name='수집 시각')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='만료 시각')),
                ('source', models.CharField(blank=True, max_length=10, verbose_name='출처')),
                ('index_code', models.CharField(max_length=10, unique=True, verbose_name='지수 코드')),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='지수')),
                ('change', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('change_pct', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
            ],
            options={
                'verbose_name': '지수 캐시',
                'verbose_name_plural': '지수 캐시',
                'db_table': 'index_cache',
            },
        ),
        migrations.CreateModel(
            name='OrderbookCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(verbose_name='수집 시각')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='만료 시각')),
                ('source', models.CharField(blank=True, max_length=10, verbose_name='출처')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('levels', models.JSONField(default=list, help_text='[{"ask_price":…, "ask_qty":…, "bid_price":…, "bid_qty":…} × 10]', verbose_name='호가 10단계')),
                ('total_ask_qty', models.DecimalField(decimal_places=8, default=0, max_digits=28, verbose_name='총 매도잔량')),
                ('total_bid_qty', models.DecimalField(decimal_places=8, default=0, max_digits=28, verbose_name='총 매수잔량')),
            ],
            options={
                'verbose_name': '호가 캐시',
                'verbose_name_plural': '호가 캐시',
                'db_table': 'orderbook_cache',
            },
        ),
        migrations.CreateModel(
            name='TradingCalendar',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='날짜(KST)')),
                ('is_open', models.BooleanField(default=True, verbose_name='개장 여부')),
                ('note', models.CharField(blank=True, max_length=50, verbose_name='비고')),
                ('source', models.CharField(choices=[('PYKRX', 'pykrx 배치'), ('MANUAL', '운영자 수정')], default='PYKRX', max_length=10)),
            ],
            options={
                'verbose_name': '영업일',
                'verbose_name_plural': '영업일',
                'db_table': 'trading_calendar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UpbitMarket',
            fields=[
                ('market', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='마켓 코드')),
                ('korean_name', models.CharField(blank=True, max_length=40, verbose_name='한글명')),
                ('english_name', models.CharField(blank=True, max_length=60, verbose_name='영문명')),
                ('is_warning', models.BooleanField(default=False, verbose_name='유의 종목')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '업비트 마켓',
                'verbose_name_plural': '업비트 마켓',
                'db_table': 'upbit_market',
            },
        ),
        migrations.CreateModel(
            name='ApiCallBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=20, verbose_name='API 이름')),
                ('window_start', models.DateTimeField(verbose_name='윈도우 시작(초 절삭)')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='호출 수')),
            ],
            options={
                'verbose_name': 'API 유량 예산',
                'verbose_name_plural': 'API 유량 예산',
                'db_table': 'api_call_budget',
                'indexes': [models.Index(fields=['window_start'], name='budget_idx_window')],
                'constraints': [models.UniqueConstraint(fields=('api_name', 'window_start'), name='budget_uniq_window')],
            },
        ),
        migrations.CreateModel(
            name='ChartCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(verbose_name='수집 시각')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='만료 시각')),
                ('source', models.CharField(blank=True, max_length=10, verbose_name='출처')),
                ('asset_class', models.CharField(choices=[('STOCK', '주식'), ('CRYPTO', '코인'), ('ALT', '대체자산')], max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('interval', models.CharField(help_text='1m / 1d / 1w 등', max_length=10, verbose_name='봉 주기')),
                ('payload', models.JSONField(default=list, verbose_name='봉 배열')),
            ],
            options={
                'verbose_name': '차트 캐시',
                'verbose_name_plural': '차트 캐시',
                'db_table': 'chart_cache',
                'constraints': [models.UniqueConstraint(fields=('asset_class', 'symbol', 'interval'), name='chart_cache_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ExternalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('KIS', '한국투자증권'), ('KB', 'KB증권'), ('ALPACA', 'Alpaca (미국주식 Paper)'), ('UPBIT', '업비트')], max_length=20, verbose_name='브로커')),
                ('environment', models.CharField(choices=[('MOCK', '모의투자 / Paper'), ('REAL', '실전 / Live')], default='MOCK', max_length=10, verbose_name='환경')),
                ('access_token', models.TextField(verbose_name='액세스 토큰')),
                ('token_type', models.CharField(default='Bearer', max_length=20, verbose_name='토큰 종류')),
                ('issued_at', models.DateTimeField(verbose_name='발급 시각')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='만료 시각')),
            ],
            options={
                'verbose_name': '외부 브로커 토큰',
                'verbose_name_plural': '외부 브로커 토큰',
                'db_table': 'external_token',
                'constraints': [models.UniqueConstraint(fields=('provider', 'environment'), name='external_token_uniq')],
            },
        ),
        migrations.CreateModel(
            name='MarketIndexSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='영업일(KST)')),
                ('index_code', models.CharField(max_length=10, verbose_name='지수 코드')),
                ('close', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='종가')),
                ('change_pct', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='등락률 %')),
            ],
            options={
                'verbose_name': '지수 일별 종가',
                'verbose_name_plural': '지수 일별 종가',
                'db_table': 'market_index_snapshot',
                'indexes': [models.Index(fields=['index_code', '-date'], name='index_snap_idx_code_date')],
                'constraints': [models.UniqueConstraint(fields=('date', 'index_code'), name='index_snapshot_uniq')],
            },
        ),
        migrations.CreateModel(
            name='NewsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(verbose_name='수집 시각')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='만료 시각')),
                ('source', models.CharField(blank=True, max_length=10, verbose_name='출처')),
                ('payload', models.JSONField(default=list, verbose_name='뉴스 목록')),
            ],
            options={
                'verbose_name': '뉴스 캐시',
                'verbose_name_plural': '뉴스 캐시',
                'db_table': 'news_cache',
                'constraints': [models.UniqueConstraint(fields=('source',), name='news_cache_uniq')],
            },
        ),
        migrations.CreateModel(
            name='QuoteCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(verbose_name='수집 시각')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='만료 시각')),
                ('source', models.CharField(blank=True, max_length=10, verbose_name='출처')),
                ('asset_class', models.CharField(choices=[('STOCK', '주식'), ('CRYPTO', '코인'), ('ALT', '대체자산')], max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='현재가')),
                ('change', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='전일 대비')),
                ('change_pct', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='등락률 %')),
                ('volume', models.BigIntegerField(default=0, verbose_name='거래량')),
                ('open', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='시가')),
                ('high', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='고가')),
                ('low', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='저가')),
                ('prev_close', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='전일 종가')),
                ('is_simulated', models.BooleanField(default=False, help_text='외부 조회가 전부 실패해 수식으로 만든 값. 대회 체결에는 절대 쓰지 않고, 연습 모드는 화면에 배지를 띄운다', verbose_name='시뮬레이션 가격')),
            ],
            options={
                'verbose_name': '현재가 캐시',
                'verbose_name_plural': '현재가 캐시',
                'db_table': 'quote_cache',
                'constraints': [models.UniqueConstraint(fields=('asset_class', 'symbol'), name='quote_cache_uniq')],
            },
        ),
        migrations.CreateModel(
            name='StockMaster',
            fields=[
                ('symbol', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='종목코드')),
                ('name', models.CharField(db_index=True, max_length=60, verbose_name='종목명')),
                ('market', models.CharField(choices=[('KOSPI', '코스피'), ('KOSDAQ', '코스닥')], max_length=10, verbose_name='시장')),
                ('stock_type', models.CharField(choices=[('COMMON', '보통주'), ('PREFERRED', '우선주'), ('ETF', 'ETF'), ('ETN', 'ETN'), ('REIT', '리츠'), ('SPAC', '스팩')], default='COMMON', max_length=15, verbose_name='종목 구분')),
                ('sector_code', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='업종 코드')),
                ('sector_name', models.CharField(blank=True, help_text='KRX 업종분류. GICS 는 MSCI·S&P 의 유료 데이터라 사용하지 않는다', max_length=40, verbose_name='업종명')),
                ('listing_date', models.DateField(blank=True, null=True, verbose_name='상장일')),
                ('market_cap', models.BigIntegerField(default=0, verbose_name='시가총액')),
                ('shares_outstanding', models.BigIntegerField(default=0, verbose_name='상장주식수')),
                ('avg_turnover_5d', models.BigIntegerField(default=0, verbose_name='5일 평균 거래대금')),
                ('close_price', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='전일 종가')),
                ('is_supervised', models.BooleanField(default=False, verbose_name='관리종목')),
                ('alert_level', models.CharField(blank=True, help_text='투자주의 / 투자경고 / 투자위험 / 환기', max_length=15, verbose_name='시장경보')),
                ('is_delisted', models.BooleanField(default=False, verbose_name='상장폐지')),
                ('is_featured', models.BooleanField(default=False, help_text='v1.0 이 하드코딩하던 14종. 시세 조회 실패 시 시뮬레이션 폴백 대상', verbose_name='수업용 14종')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '종목 마스터',
                'verbose_name_plural': '종목 마스터',
                'db_table': 'stock_master',
                'indexes': [models.Index(fields=['market', 'stock_type', 'is_delisted'], name='stock_idx_tradable'), models.Index(fields=['-market_cap'], name='stock_idx_market_cap')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(choices=[('STOCK', '주식'), ('CRYPTO', '코인'), ('ALT', '대체자산')], max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=4, verbose_name='우선순위')),
                ('reason', models.CharField(blank=True, max_length=20, verbose_name='근거')),
                ('last_polled_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 폴링')),
                ('expires_at', models.DateTimeField(blank=True, help_text='화면 열람(우선순위 3)은 일정 시간 후 만료된다', null=True, verbose_name='만료')),
            ],
            options={
                'verbose_name': '시세 구독',
                'verbose_name_plural': '시세 구독',
                'db_table': 'subscription_registry',
                'indexes': [models.Index(fields=['priority', 'last_polled_at'], name='subs_idx_priority_polled')],
                'constraints': [models.UniqueConstraint(fields=('asset_class', 'symbol'), name='subs_uniq_symbol')],
            },
        ),
    ]
