# Generated by Django 5.2.17 on 2026-08-13 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeProduct',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='심볼')),
                ('name', models.CharField(max_length=50, verbose_name='상품명')),
                ('category', models.CharField(help_text='선물/옵션/파생상품/금/은/부동산', max_length=20, verbose_name='분류')),
                ('base_price', models.BigIntegerField(default=0, verbose_name='기준가')),
                ('multiplier', models.IntegerField(default=1, verbose_name='승수')),
                ('unit_label', models.CharField(blank=True, help_text='1계약 · 1g · 1구좌', max_length=20, verbose_name='단위')),
                ('margin_rate_pct', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='증거금률 %')),
                ('volatility_pct', models.DecimalField(decimal_places=4, default=0, help_text='옵션·파생 1.8 / 나머지 0.9', max_digits=9, verbose_name='일간 진폭 %')),
                ('point_scale', models.IntegerField(blank=True, null=True, verbose_name='포인트 배율')),
                ('actual_multiplier', models.IntegerField(blank=True, help_text='FUT-K200 실계약 규모 안내용', null=True, verbose_name='실계약 승수')),
                ('map_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='위도')),
                ('map_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='경도')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('sort_order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '대체자산 상품',
                'verbose_name_plural': '대체자산 상품',
                'db_table': 'alternative_product',
                'ordering': ['sort_order', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, help_text='주식 005930 · 코인 KRW-BTC · 대체자산 FUT-K200', max_length=20, verbose_name='종목')),
                ('asset_class', models.CharField(choices=[('STOCK', '주식'), ('CRYPTO', '코인'), ('ALT', '대체자산')], help_text='조인 없이 필터하려고 저장한다 (규약 8.1)', max_length=10, verbose_name='자산군')),
                ('side', models.CharField(choices=[('BUY', '매수'), ('SELL', '매도')], max_length=4, verbose_name='매매 구분')),
                ('order_type', models.CharField(choices=[('MARKET', '시장가'), ('LIMIT', '지정가'), ('RELATIVE', '상대호가'), ('OWN', '자기호가'), ('STOP', 'STOP')], max_length=12, verbose_name='주문 유형')),
                ('price_level', models.PositiveSmallIntegerField(blank=True, help_text='상대호가·자기호가일 때만 1~10', null=True, verbose_name='호가 단계')),
                ('limit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='지정가')),
                ('stop_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='STOP 발동가')),
                ('requested_weight_pct', models.DecimalField(blank=True, decimal_places=4, help_text='대회 모드는 수량이 아니라 순자산 대비 %로 주문한다(F-03 3.1). 연습은 비운다', max_digits=9, null=True, verbose_name='주문 비중 %')),
                ('requested_qty', models.DecimalField(decimal_places=8, max_digits=28, verbose_name='요청 수량')),
                ('filled_qty', models.DecimalField(decimal_places=8, default=0, max_digits=28, verbose_name='체결 수량')),
                ('avg_fill_price', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='가중평균 체결가')),
                ('gross_amount', models.BigIntegerField(default=0, verbose_name='체결금액(수수료 전)')),
                ('fee', models.BigIntegerField(default=0, verbose_name='수수료')),
                ('tax', models.BigIntegerField(default=0, verbose_name='매도세')),
                ('net_amount', models.BigIntegerField(default=0, verbose_name='정산금액')),
                ('realized_pnl', models.BigIntegerField(blank=True, help_text='매도 체결 시 계산해 저장한다. 사후 계산 없이 합산할 수 있게 한다', null=True, verbose_name='실현손익')),
                ('status', models.CharField(choices=[('PENDING_OPEN', '장 시작 대기'), ('ACCEPTED', '접수'), ('PARTIAL', '부분체결'), ('FILLED', '체결완료'), ('CANCELLED', '취소'), ('REJECTED', '거부')], db_index=True, default='ACCEPTED', max_length=15, verbose_name='상태')),
                ('source', models.CharField(choices=[('WEB', '웹'), ('PINE', 'Pine 전략'), ('OPENAPI', 'Open API'), ('ADMIN', '운영자'), ('DEMO_SEED', '샘플')], default='WEB', max_length=10, verbose_name='주문 경로')),
                ('execution_mode', models.CharField(default='IMMEDIATE', help_text='SLICED(시간분할)는 v2.1. 컬럼만 미리 만들어 둔다', max_length=10, verbose_name='체결 방식')),
                ('reject_rule', models.CharField(blank=True, max_length=30, verbose_name='위반 규칙')),
                ('reject_message', models.CharField(blank=True, max_length=200, verbose_name='거부 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.account', verbose_name='계좌')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(verbose_name='조각 순번')),
                ('qty', models.DecimalField(decimal_places=8, max_digits=28, verbose_name='체결 수량')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='체결가')),
                ('amount', models.BigIntegerField(default=0, verbose_name='체결금액')),
                ('price_level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='체결 호가 단계')),
                ('is_assumed_depth', models.BooleanField(default=False, help_text='10호가를 넘어 가정으로 체결된 조각. 체결 상세에 배지를 띄운다', verbose_name='추정 잔량 체결')),
                ('executed_at', models.DateTimeField(verbose_name='체결 시각')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='trading.order', verbose_name='주문')),
            ],
            options={
                'verbose_name': '체결',
                'verbose_name_plural': '체결',
                'db_table': 'execution',
                'ordering': ['order', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='AvgDownSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='종목')),
                ('params', models.JSONField(default=dict, help_text='보유수량·평단·추가매수가·수량/금액', verbose_name='입력값')),
                ('result', models.JSONField(default=dict, help_text='새 평단·본전 상승률·잔여현금', verbose_name='산출값')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avg_down_simulations', to='accounts.account')),
                ('executed_order', models.ForeignKey(blank=True, help_text='시뮬레이션이 실제 주문으로 이어졌으면 연결한다', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avg_down_simulations', to='trading.order', verbose_name='실행된 주문')),
            ],
            options={
                'verbose_name': '물타기 시뮬레이션',
                'verbose_name_plural': '물타기 시뮬레이션',
                'db_table': 'avg_down_simulation',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='종목')),
                ('asset_class', models.CharField(choices=[('STOCK', '주식'), ('CRYPTO', '코인'), ('ALT', '대체자산')], max_length=10, verbose_name='자산군')),
                ('qty', models.DecimalField(decimal_places=8, default=0, max_digits=28, verbose_name='수량')),
                ('avg_price', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='평균 단가')),
                ('principal', models.BigIntegerField(default=0, verbose_name='매수원금')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='accounts.account', verbose_name='계좌')),
            ],
            options={
                'verbose_name': '보유 포지션',
                'verbose_name_plural': '보유 포지션',
                'db_table': 'position',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['account', '-created_at'], name='order_idx_account_recent'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['account', 'asset_class', 'side'], name='order_idx_account_class'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('status__in', ['ACCEPTED', 'PARTIAL', 'PENDING_OPEN'])), fields=['symbol', 'status'], name='order_idx_open'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('filled_qty__lte', models.F('requested_qty'))), name='order_ck_filled_le_requested'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.UniqueConstraint(fields=('order', 'seq'), name='execution_uniq_order_seq'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['symbol'], name='position_idx_symbol'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('account', 'symbol'), name='position_uniq_account_symbol'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gte', 0)), name='position_ck_qty_nonneg'),
        ),
    ]
