# Generated by Django 5.2.17 on 2026-08-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativeproduct',
            name='description',
            field=models.CharField(blank=True, help_text='시세 표·선택 안내줄에 그대로 노출된다 (v1.0 CATALOG.description)', max_length=100, verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='alternativeproduct',
            name='map_label',
            field=models.CharField(blank=True, help_text="'서울 강남구' 등. Leaflet 마커 팝업과 차트 부제에 쓴다", max_length=40, verbose_name='지도 표시명'),
        ),
    ]
