# Generated by Django 5.2.17 on 2026-08-13 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJobRunDetail',
            fields=[
                ('jobid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('runid', models.BigIntegerField()),
                ('command', models.TextField()),
                ('status', models.TextField()),
                ('return_message', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'pg_cron 실행 이력',
                'verbose_name_plural': 'pg_cron 실행 이력',
                'db_table': 'cron"."job_run_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='키')),
                ('value', models.JSONField(verbose_name='값')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '앱 설정',
                'verbose_name_plural': '앱 설정',
                'db_table': 'app_setting',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='DataSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(db_index=True, max_length=40, verbose_name='잡 이름')),
                ('started_at', models.DateTimeField(db_index=True, verbose_name='시작 시각')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시각')),
                ('status', models.CharField(choices=[('RUNNING', '실행중'), ('SUCCESS', '성공'), ('FAILED', '실패')], default='RUNNING', max_length=10, verbose_name='상태')),
                ('rows_affected', models.IntegerField(default=0, verbose_name='처리 행 수')),
                ('error', models.TextField(blank=True, verbose_name='스택트레이스')),
                ('triggered_by', models.CharField(choices=[('CRON', '스케줄러'), ('ADMIN', '운영자'), ('CLI', '커맨드')], default='CRON', max_length=10, verbose_name='실행 주체')),
            ],
            options={
                'verbose_name': '배치 실행 이력',
                'verbose_name_plural': '배치 실행 이력',
                'db_table': 'data_sync_log',
                'indexes': [models.Index(fields=['job_name', '-started_at'], name='sync_log_idx_job_recent'), models.Index(condition=models.Q(('status', 'FAILED')), fields=['-started_at'], name='sync_log_idx_failed')],
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text='DISQUALIFY / RESTORE / RESETTLE / RULE_CHANGE / ORDER_EDIT', max_length=40, verbose_name='조치')),
                ('target_model', models.CharField(max_length=40, verbose_name='대상 모델')),
                ('target_id', models.CharField(help_text='StockMaster 처럼 문자열 PK 인 모델도 있어서 varchar 로 둔다', max_length=40, verbose_name='대상 PK')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='변경 전')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='변경 후')),
                ('reason', models.CharField(help_text='실격·주문수정·정산재실행·규칙변경은 사유 입력이 필수다', max_length=200, verbose_name='사유')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='조치자')),
            ],
            options={
                'verbose_name': '운영자 감사 로그',
                'verbose_name_plural': '운영자 감사 로그',
                'db_table': 'admin_audit_log',
                'indexes': [models.Index(fields=['target_model', 'target_id'], name='audit_idx_target')],
            },
        ),
    ]
